ALTER TABLE AF_APPLICATION 
MODIFY APPLICATION_KEY VARCHAR(19) NOT NULL,
MODIFY APPLICATION_NAME VARCHAR(50) NOT NULL ,
MODIFY TENANT_ID INT(5) NOT NULL,
MODIFY STATUS VARCHAR(10) NOT NULL DEFAULT 'PENDING',
ADD INDEX (APPLICATION_KEY, TENANT_ID);

ALTER TABLE AF_VERSION 
MODIFY STAGE VARCHAR(20) DEFAULT 'Development',
MODIFY PROMOTE_STATUS VARCHAR(20) NULL,
ADD AUTO_BUILD TINYINT(1) DEFAULT 1,
ADD AUTO_DEPLOY TINYINT(1) DEFAULT 1,
ADD SUBDOMAIN VARCHAR(50) NULL,
ADD TENANT_ID INT(5) NOT NULL,
ADD INDEX (APPLICATION_ID, VERSION_NAME);

ALTER TABLE AF_REPOSITORY
CHANGE REPOSITORY_IS_FORK IS_FORKED TINYINT(1) DEFAULT 0,
CHANGE USER_ID GIT_USER_ID VARCHAR(50) NULL,
ADD TENANT_ID INT(5) NOT NULL,
ADD INDEX (VERSION_ID, IS_FORKED);

ALTER TABLE AF_BUILD
DROP COLUMN CURRENT_BUILD,
ADD TENANT_ID INT(5) NOT NULL,
CHANGE LAST_BUILD LAST_BUILD_ID VARCHAR(10) NULL,
MODIFY LAST_BUILD_STATUS VARCHAR(10) NULL,
ADD INDEX (REPOSITORY_ID);

ALTER TABLE AF_DEPLOY
ADD TENANT_ID INT(5) NOT NULL,
CHANGE LAST_DEPLOY LAST_DEPLOYED_BUILD_ID VARCHAR(10) NULL,
MODIFY LAST_DEPLOY_STATUS VARCHAR(15) NULL,
MODIFY ENVIRONMENT VARCHAR(20) NULL,
ADD INDEX (REPOSITORY_ID);

ALTER TABLE AF_RESOURCE
ADD TENANT_ID INT(5) NOT NULL,
MODIFY RESOURCE_TYPE VARCHAR(50) NOT NULL,
MODIFY RESOURCE_NAME VARCHAR(50) NOT NULL,
MODIFY ENVIRONMENT VARCHAR(20) NOT NULL,
ADD INDEX (RESOURCE_TYPE, ENVIRONMENT),
ADD INDEX (APPLICATION_ID);

ALTER TABLE AF_CARTRIDGE_CLUSTER
ADD TENANT_ID INT(5) NOT NULL,
MODIFY CLUSTER_ID VARCHAR(11) NOT NULL,
MODIFY LB_CLUSTER_ID VARCHAR(11),
MODIFY ACTIVE_IP VARCHAR(20) NOT NULL,
ADD INDEX (CLUSTER_ID);

SET SQL_SAFE_UPDATES=0;
UPDATE AF_APPLICATION APP JOIN AF_VERSION VERSION ON APP.ID=VERSION.APPLICATION_ID SET VERSION.TENANT_ID= APP.TENANT_ID;
UPDATE AF_APPLICATION APP JOIN AF_RESOURCE RES ON APP.ID=RES.APPLICATION_ID SET RES.TENANT_ID= APP.TENANT_ID;
UPDATE AF_REPOSITORY REPO JOIN AF_VERSION VERSION ON REPO.VERSION_ID=VERSION.ID SET REPO.TENANT_ID=VERSION.TENANT_ID;
UPDATE AF_REPOSITORY REPO JOIN AF_BUILD BUILD ON BUILD.REPOSITORY_ID=REPO.ID SET BUILD.TENANT_ID=REPO.TENANT_ID;
UPDATE AF_REPOSITORY REPO JOIN AF_DEPLOY DEPLOY ON DEPLOY.REPOSITORY_ID=REPO.ID SET DEPLOY.TENANT_ID=REPO.TENANT_ID;
SET SQL_SAFE_UPDATES=1;


